name: Bug Report
description: File a bug report for something that isn't working as expected
labels: [bug]
title: "[BUG] "
body:
  - type: markdown
    attributes:
      value: |
        Please describe the issue you encountered. Avoid sharing any proprietary code or internal systems unless you’re cleared to do so.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide steps someone could use to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: What should have happened if the bug weren’t there?
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment (OS, Browser, CLI, etc.)
      description: Optional details that might help us debug it.
    validations:
      required: false