name: Secrets Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Search for potential secrets
        run: |
          echo "🔍 Scanning for .env files or exposed keys..."
          if grep -rE --exclude-dir={.git,node_modules,.venv,__pycache__} \
            'api[_-]?key\s*=\s*["'\'']?[A-Za-z0-9]{16,}' . || \
             find . -type f -name '*.env'; then
            echo "::error file=.,line=1::⚠️ Potential secret or .env pattern found"
            exit 1
          else
            echo "✅ No secrets detected"
          fi